export const MapActionTypes = {
    FETCH_MAP_DATA_START: 'FETCH_MAP_DATA_START',
    UPDATE_CURRENT_TIME: 'UPDATE_CURRENT_TIME',
    UPDATE_SELECTED: 'UPDATE_SELECTED',
    FETCH_POSTCODE_DATA: 'FETCH_POSTCODE_DATA',
    UPDATE_POSTCODE_DATA: 'UPDATE_POSTCODE_DATA',
}